import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useAuth } from "@/context/auth-context-core";
import { api, getErrorMessage } from "@/lib/api";
import { type User, type Club } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertCircle, Check, Loader2 } from "lucide-react";
import { MembershipStatus } from "@/components/membership-status";
import { PaymentDetails } from "@/components/payment-details";

export function ProfilePage() {
    const { t } = useTranslation();
    const { user, token, apiUpdateUser, login } = useAuth();
    const [loading, setLoading] = useState(false);
    const [message, setMessage] = useState<string | null>(null);
    const [error, setError] = useState<string | null>(null);

    // Membership Actions Modal State
    const [actionModal, setActionModal] = useState<'apply' | 'cancel' | null>(null);
    const [actionDate, setActionDate] = useState<string>(new Date().toISOString().split('T')[0]);
    const [actionError, setActionError] = useState<string | null>(null);
    const [actionLoading, setActionLoading] = useState(false);

    const [searchParams] = useSearchParams();
    const typeQuery = searchParams.get("type");
    const [applyType, setApplyType] = useState<'active' | 'supporting'>(typeQuery === "supporting" ? "supporting" : "active");
    const [applyFee, setApplyFee] = useState<number>(30);

    const [consents, setConsents] = useState({
        privacy: false,
        accuracy: false,
        statutes: false,
        finances: false
    });
    const [clubMatch, setClubMatch] = useState<{ name: string; status: string } | null>(null);

    const [formData, setFormData] = useState<{
        firstname: string;
        lastname: string;
        email: string;
        language: string;
        your_club: string;
        address: string;
        iban?: string;
        account_holder?: string;
        sepa_mandate_number?: string;
    }>({
        firstname: '',
        lastname: '',
        email: '',
        language: '',
        your_club: '',
        address: ''
    });

    useEffect(() => {
        if (user) {
            setFormData(prev => ({
                ...prev,
                firstname: user.firstname || '',
                lastname: user.lastname || '',
                email: user.email || '',
                language: user.language || 'default',
                your_club: user.your_club || '',
                address: user.membership?.address || ''
            }));
        }
    }, [user]);

    useEffect(() => {
        const timer = setTimeout(async () => {
            if (formData.your_club && formData.your_club.length >= 3 && token) {
                try {
                    const matches = await api.get<Club[]>(`/clubs/search?q=${encodeURIComponent(formData.your_club)}`, token);
                    const exactMatch = matches.find(c => c.name.toLowerCase() === formData.your_club.toLowerCase());
                    if (exactMatch && exactMatch.membership.status === 'active') {
                        setClubMatch({ name: exactMatch.name, status: exactMatch.membership.status });
                    } else {
                        setClubMatch(null);
                    }
                } catch (e) {
                    console.error("Club search failed", e);
                    setClubMatch(null);
                }
            } else {
                setClubMatch(null);
            }
        }, 500);
        return () => clearTimeout(timer);
    }, [formData.your_club, token]);

    const handleMembershipAction = async (action: 'apply' | 'cancel') => {
        if (!token) return;
        setActionLoading(true);
        setActionError(null);

        // Convert date string to unix seconds if present
        const unixSeconds = actionDate ? Math.floor(new Date(actionDate).getTime() / 1000) : 0;

        // For apply, pass consents instead of date. Date is auto-generated by backend.
        const payload = action === 'apply'
            ? {
                consent_privacy: consents.privacy,
                consent_accuracy: consents.accuracy,
                consent_statutes: consents.statutes,
                consent_finances: consents.finances,
                type: applyType,
                fee: applyType === 'supporting' ? applyFee : 10
            }
            : { end_date: unixSeconds };

        try {
            await api.post(`/users/me/${action}`, payload, token);
            // Refresh user to get updated membership status
            const updatedUser = await api.get<User>('/users/me', token);
            if (apiUpdateUser) apiUpdateUser(updatedUser);
            setActionModal(null);
        } catch (err: unknown) {
            console.error(err);
            setActionError(getErrorMessage(err, t));
        } finally {
            setActionLoading(false);
        }
    };

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!token || !user) return;
        setLoading(true);
        setMessage(null);
        setError(null);
        if (user.membership?.status === 'active' && !formData.your_club) {
            setError(t('profile.messages.your_club_required', { defaultValue: 'Bitte gib deinen Verein an.' }));
            setLoading(false);
            return;
        }
        try {
            const updated = await api.patch<User>('/users/me', formData, token);
            // Update context - login function usually updates user in context
            // If check useAuth implementation (I don't have it open, but usage suggests login/apiUpdateUser)
            // The file initially used apiUpdateUser.
            if (apiUpdateUser) {
                apiUpdateUser(updated);
            } else if (login) {
                login(token, updated);
            }

            const messages = [t('profile.messages.success')];

            // Request Email Validation if changed
            if (formData.email !== user?.email) {
                await api.post('/users/request-email-validation', {
                    email: formData.email
                }, token);
                messages.push(t('profile.messages.email_sent', { email: formData.email }));
            }

            setMessage(messages.join(" "));
            setError(null); // Clear any previous errors on success
        } catch (err: unknown) {
            setError(getErrorMessage(err, t));
        } finally {
            setLoading(false);
        }
    };

    // Language options - use "default" as tombstone to clear backend language preference
    const languages = [
        { code: "default", label: t('profile.language_options.browser_default') },
        { code: "de", label: "🇩🇪 Deutsch" },
        { code: "en", label: "🇬🇧 English" },
        { code: "es", label: "🇪🇸 Español" },
        { code: "fr", label: "🇫🇷 Français" },
        { code: "pl", label: "🇵🇱 Polski" },
        { code: "ro", label: "🇷🇴 Română" },
        { code: "sq", label: "🇦🇱 Shqip" },
        { code: "tr", label: "🇹🇷 Türkçe" },
        { code: "ru", label: "🇷🇺 Русский" },
        { code: "uk", label: "🇺🇦 Українська" },
        { code: "ar", label: "🇸🇦 العربية" },
    ];

    if (!user) return null;

    return (
        <div className="max-w-2xl mx-auto space-y-6 pb-12">
            <h1 className="text-2xl font-bold">{t('profile.title')}</h1>

            <form onSubmit={handleSave}>
                <Card>
                    <CardHeader>
                        <CardTitle>{t('profile.personal_data.title')}</CardTitle>
                        <CardDescription>{t('profile.personal_data.description')}</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        {message && (
                            <div className="bg-green-100 text-green-700 p-3 rounded-md flex items-center gap-2">
                                <Check className="h-4 w-4" /> {message}
                            </div>
                        )}
                        {error && (
                            <div className="bg-destructive/10 text-destructive p-3 rounded-md flex items-center gap-2">
                                <AlertCircle className="h-4 w-4" /> {error}
                            </div>
                        )}

                        <div className="grid md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="firstname">{t('profile.labels.firstname')}</Label>
                                <Input
                                    id="firstname"
                                    name="firstname"
                                    value={formData.firstname}
                                    onChange={handleChange}
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="lastname">{t('profile.labels.lastname')}</Label>
                                <Input
                                    id="lastname"
                                    name="lastname"
                                    value={formData.lastname}
                                    onChange={handleChange}
                                />
                            </div>
                        </div>

                        <div className="grid md:grid-cols-2 gap-4 mb-4">
                            <div className="space-y-2">
                                <Label htmlFor="address">Adresse</Label>
                                <Input
                                    id="address"
                                    name="address"
                                    value={formData.address}
                                    onChange={handleChange}
                                    placeholder="Straße, PLZ, Ort"
                                />
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="your_club">{t('profile.labels.yourClub', { defaultValue: 'Dein Verein' })}</Label>
                                <Input
                                    id="your_club"
                                    name="your_club"
                                    value={formData.your_club}
                                    onChange={handleChange}
                                    placeholder="Optional"
                                />
                                {clubMatch && user.membership?.status === 'active' && (
                                    <p className="text-xs text-amber-600 dark:text-amber-400 mt-1 flex items-start gap-1">
                                        <AlertCircle className="h-3 w-3 mt-0.5 shrink-0" />
                                        {t('profile.messages.your_club_is_member', { name: clubMatch.name })}
                                    </p>
                                )}
                            </div>
                        </div>

                        <PaymentDetails
                            token={token!}
                            fetchUrl="/users/me/payment-details"
                            isAdmin={user?.roles?.includes('admin') || user?.roles?.includes('owner')}
                            formData={formData}
                            onChange={(field, val) => setFormData(p => ({ ...p, [field]: val }))}
                            isReadOnly={false}
                            alwaysOpen={false}
                        />

                        <div className="space-y-2 mt-4">
                            <Label htmlFor="email">{t('profile.labels.email')}</Label>
                            <Input
                                id="email"
                                name="email"
                                value={formData.email}
                                onChange={handleChange}
                            />
                            {formData.email !== user?.email && (
                                <p className="text-xs text-amber-600 dark:text-amber-400 flex items-center gap-1">
                                    <AlertCircle className="h-3 w-3" />
                                    {t('profile.messages.email_validation_required')}
                                </p>
                            )}
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="language">{t('profile.labels.language')}</Label>
                            <select
                                id="language"
                                name="language"
                                value={formData.language}
                                onChange={handleChange}
                                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                            >
                                {languages.map(l => (
                                    <option key={l.code} value={l.code}>{l.label}</option>
                                ))}
                            </select>
                        </div>

                    </CardContent>
                    <CardFooter>
                        <Button type="submit" disabled={loading}>
                            {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                            {t('profile.actions.save')}
                        </Button>
                    </CardFooter>
                </Card>
            </form>

            <Card>
                <CardHeader>
                    <CardTitle>Mitgliedschaft</CardTitle>
                    <CardDescription>Verwalte deine Mitgliedschaft im DPV</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    {actionError && (
                        <div className="bg-destructive/10 text-destructive p-3 rounded-md flex items-center gap-2">
                            <AlertCircle className="h-4 w-4" /> {actionError}
                        </div>
                    )}

                    <div className="p-4 border rounded-md bg-muted/20">
                        <MembershipStatus membership={user?.membership} />
                    </div>

                    <div className="flex justify-end mt-4">
                        {(user?.membership?.status === 'active' || user?.membership?.status === 'requested') ? (
                            <Button size="sm" variant="outline" className="text-destructive hover:text-destructive" onClick={() => {
                                if (user?.membership?.status === 'requested') {
                                    if (confirm("Möchtest du deinen Antrag wirklich zurückziehen?")) {
                                        handleMembershipAction('cancel');
                                    }
                                } else {
                                    setActionModal('cancel');
                                }
                            }} disabled={actionLoading}>
                                {actionLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                                {user?.membership?.status === 'active' ? 'Kündigen' : 'Antrag zurückziehen'}
                            </Button>
                        ) : (
                            <Button size="sm" onClick={() => setActionModal('apply')} disabled={actionLoading}>
                                {actionLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                                {(user?.membership?.status === 'cancelled' || user?.membership?.status === 'denied')
                                    ? 'Erneut beantragen'
                                    : 'Mitgliedschaft beantragen'}
                            </Button>
                        )}
                    </div>
                </CardContent>
            </Card>

            {/* Verbandsdaten (Read-Only) */}
            <Card>
                <CardHeader>
                    <CardTitle>{t('profile.verband.title', { defaultValue: 'Verbandsdaten' })}</CardTitle>
                    <CardDescription>{t('profile.verband.description', { defaultValue: 'Wird vom Verband ausgefüllt' })}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="grid md:grid-cols-2 gap-4">
                        <div className="space-y-2">
                            <Label>{t('profile.verband.membership_number', { defaultValue: 'Mitgliedsnummer' })}</Label>
                            <Input value={user?.membership?.membership_number || ''} disabled />
                        </div>
                        <div className="space-y-2">
                            <Label>{t('profile.verband.fee', { defaultValue: 'Aktueller Beitrag' })}</Label>
                            <Input value={user.membership?.current_fee !== undefined ? `${user.membership.current_fee.toFixed(2)} €` : ''} disabled />
                            <p className="text-xs text-muted-foreground mt-1">Siehe <a href="#" target="_blank" className="underline">Satzung</a> und <a href="#" target="_blank" className="underline">Beitragsordnung</a></p>
                        </div>
                    </div>
                </CardContent>
            </Card>

            {/* Action Modal equivalent inline */}
            {
                actionModal && (
                    <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4">
                        <Card className="w-full max-w-md shadow-lg border">
                            <CardHeader>
                                <CardTitle>
                                    {actionModal === 'apply' ? 'Mitgliedschaft beantragen' : 'Mitgliedschaft kündigen'}
                                </CardTitle>
                                <CardDescription>
                                    {actionModal === 'apply'
                                        ? 'Bitte wähle aus, ab wann du aktiv werden möchtest.'
                                        : 'Bitte wähle aus, zu wann du kündigen möchtest.'}
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-4">
                                {actionModal === 'cancel' ? (
                                    <div className="space-y-2">
                                        <Label htmlFor="actionDate">Ende (Optional)</Label>
                                        <Input
                                            id="actionDate"
                                            type="date"
                                            value={actionDate}
                                            onChange={(e) => setActionDate(e.target.value)}
                                        />
                                        <p className="text-xs text-muted-foreground pt-1">
                                            Wenn du das Datum leer lässt, wird die Kündigung sofort wirksam.
                                        </p>
                                    </div>
                                ) : (
                                    <div className="space-y-4 pt-2">
                                        <div className="space-y-2 border-b pb-4">
                                            <Label>Art der Mitgliedschaft</Label>
                                            <div className="flex flex-col gap-2">
                                                <Label className="flex items-center gap-2 cursor-pointer font-normal">
                                                    <input type="radio" value="active" checked={applyType === 'active'} onChange={() => setApplyType('active')} />
                                                    Aktivmitgliedschaft (10 € / Jahr)
                                                </Label>
                                                <Label className="flex items-center gap-2 cursor-pointer font-normal">
                                                    <input type="radio" value="supporting" checked={applyType === 'supporting'} onChange={() => setApplyType('supporting')} />
                                                    Fördernde Mitgliedschaft
                                                </Label>
                                            </div>
                                        </div>
                                        {applyType === 'supporting' && (
                                            <div className="space-y-2 animate-in fade-in pb-2">
                                                <Label htmlFor="customFee">Wunschbeitrag pro Jahr (€)</Label>
                                                <Input
                                                    id="customFee"
                                                    type="number"
                                                    min="1"
                                                    step="1"
                                                    value={applyFee}
                                                    onChange={(e) => setApplyFee(Number(e.target.value))}
                                                />
                                            </div>
                                        )}
                                        <div className="space-y-3">
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-privacy" className="mt-1" checked={consents.privacy} onChange={(e) => setConsents(p => ({ ...p, privacy: e.target.checked }))} />
                                                <Label htmlFor="consent-privacy" className="text-sm font-normal leading-snug">
                                                    {t('club.details.membership.consent_privacy', { defaultValue: 'Ich stimme der Datenschutzerklärung zu.' })}
                                                </Label>
                                            </div>
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-accuracy" className="mt-1" checked={consents.accuracy} onChange={(e) => setConsents(p => ({ ...p, accuracy: e.target.checked }))} />
                                                <Label htmlFor="consent-accuracy" className="text-sm font-normal leading-snug">
                                                    {t('club.details.membership.consent_accuracy', { defaultValue: 'Ich versichere, dass meine Angaben der Wahrheit entsprechen.' })}
                                                </Label>
                                            </div>
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-statutes" className="mt-1" checked={consents.statutes} onChange={(e) => setConsents(p => ({ ...p, statutes: e.target.checked }))} />
                                                <Label htmlFor="consent-statutes" className="text-sm font-normal leading-snug">
                                                    Ich habe die <a href="#" target="_blank" className="underline text-blue-600">Satzung</a> gelesen und erkenne sie an.
                                                </Label>
                                            </div>
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-finances" className="mt-1" checked={consents.finances} onChange={(e) => setConsents(p => ({ ...p, finances: e.target.checked }))} />
                                                <Label htmlFor="consent-finances" className="text-sm font-normal leading-snug">
                                                    Ich habe die <a href="#" target="_blank" className="underline text-blue-600">Beitragsordnung</a> gelesen und erkenne sie an.
                                                </Label>
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </CardContent>
                            <CardFooter className="justify-end gap-2 bg-muted/20 py-4">
                                <Button variant="ghost" onClick={() => setActionModal(null)} disabled={actionLoading}>
                                    {t('club.details.actions.cancel', { defaultValue: 'Abbrechen' })}
                                </Button>
                                <Button
                                    variant={actionModal === 'apply' ? 'default' : 'destructive'}
                                    onClick={() => handleMembershipAction(actionModal)}
                                    disabled={actionLoading || (actionModal === 'apply' && (!consents.privacy || !consents.accuracy || !consents.statutes || !consents.finances))}
                                >
                                    {actionLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                                    {actionModal === 'apply' ? t('club.details.membership.apply_button', { defaultValue: 'Antrag stellen' }) : t('club.details.membership.cancel_button', { defaultValue: 'Kündigen' })}
                                </Button>
                            </CardFooter>
                        </Card>
                    </div>
                )
            }
        </div >
    );
}
