import { useState } from "react";
import { useSearchParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useAuth } from "@/context/auth-context-core";
import { api, getErrorMessage } from "@/lib/api";
import { type User } from "@/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertCircle, Loader2 } from "lucide-react";
import { MembershipStatus } from "@/components/membership-status";
import { UserProfileForm } from "@/components/user-profile-form";

export function ProfilePage() {
    const { t } = useTranslation();
    const { user, token, apiUpdateUser, login } = useAuth();


    // Membership Actions Modal State
    const [actionModal, setActionModal] = useState<'apply' | 'cancel' | null>(null);
    const [actionDate, setActionDate] = useState<string>(new Date().toISOString().split('T')[0]);
    const [actionError, setActionError] = useState<string | null>(null);
    const [actionLoading, setActionLoading] = useState(false);

    const [searchParams] = useSearchParams();
    const typeQuery = searchParams.get("type");
    const [applyType, setApplyType] = useState<'active' | 'supporting'>(typeQuery === "supporting" ? "supporting" : "active");
    const [applyFee, setApplyFee] = useState<number>(30);

    const [consents, setConsents] = useState({
        privacy: false,
        accuracy: false,
        statutes: false,
        finances: false
    });
    const handleMembershipAction = async (action: 'apply' | 'cancel') => {
        if (!token) return;
        setActionLoading(true);
        setActionError(null);

        // Convert date string to unix seconds if present
        const unixSeconds = actionDate ? Math.floor(new Date(actionDate).getTime() / 1000) : 0;

        // For apply, pass consents instead of date. Date is auto-generated by backend.
        const payload = action === 'apply'
            ? {
                consent_privacy: consents.privacy,
                consent_accuracy: consents.accuracy,
                consent_statutes: consents.statutes,
                consent_finances: consents.finances,
                type: applyType,
                fee: applyType === 'supporting' ? applyFee : 10
            }
            : { end_date: unixSeconds };

        try {
            await api.post(`/users/me/${action}`, payload, token);
            // Refresh user to get updated membership status
            const updatedUser = await api.get<User>('/users/me', token);
            if (apiUpdateUser) apiUpdateUser(updatedUser);
            setActionModal(null);
        } catch (err: unknown) {
            console.error(err);
            setActionError(getErrorMessage(err, t));
        } finally {
            setActionLoading(false);
        }
    };

    const handleSaveSuccess = (updatedUser: User) => {
        if (apiUpdateUser) {
            apiUpdateUser(updatedUser);
        } else if (login && token) {
            login(token, updatedUser);
        }
        // Notification is handled inside UserProfileForm already,
        // but we could lift state up if we needed app-wide toast.
    };

    if (!user) return null;

    return (
        <div className="max-w-2xl mx-auto space-y-6 pb-12">
            <h1 className="text-2xl font-bold">{t('profile.title')}</h1>

            <UserProfileForm
                user={user}
                token={token!}
                onSaveSuccess={handleSaveSuccess}
            />

            <Card>
                <CardHeader>
                    <CardTitle>Mitgliedschaft</CardTitle>
                    <CardDescription>Verwalte deine Mitgliedschaft im DPV</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    {actionError && (
                        <div className="bg-destructive/10 text-destructive p-3 rounded-md flex items-center gap-2">
                            <AlertCircle className="h-4 w-4" /> {actionError}
                        </div>
                    )}

                    <div className="p-4 border rounded-md bg-muted/20">
                        <MembershipStatus membership={user?.membership} />
                    </div>

                    <div className="flex justify-end mt-4">
                        {(user?.membership?.status === 'active' || user?.membership?.status === 'requested') ? (
                            <Button size="sm" variant="outline" className="text-destructive hover:text-destructive" onClick={() => {
                                if (user?.membership?.status === 'requested') {
                                    if (confirm("Möchtest du deinen Antrag wirklich zurückziehen?")) {
                                        handleMembershipAction('cancel');
                                    }
                                } else {
                                    setActionModal('cancel');
                                }
                            }} disabled={actionLoading}>
                                {actionLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                                {user?.membership?.status === 'active' ? t('profile.actions.cancel_membership') : t('profile.actions.withdraw_application')}
                            </Button>
                        ) : (
                            <Button size="sm" onClick={() => setActionModal('apply')} disabled={actionLoading}>
                                {actionLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                                {(user?.membership?.status === 'cancelled' || user?.membership?.status === 'denied')
                                    ? t('profile.actions.reapply')
                                    : t('profile.actions.apply_membership')}
                            </Button>
                        )}
                    </div>
                </CardContent>
            </Card>

            {/* Verbandsdaten (Read-Only) */}
            <Card>
                <CardHeader>
                    <CardTitle>{t('profile.verband.title', { defaultValue: 'Verbandsdaten' })}</CardTitle>
                    <CardDescription>{t('profile.verband.description', { defaultValue: 'Wird vom Verband ausgefüllt' })}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="grid md:grid-cols-2 gap-4">
                        <div className="space-y-2">
                            <Label>{t('profile.verband.membership_number', { defaultValue: 'Mitgliedsnummer' })}</Label>
                            <Input value={user?.membership?.membership_number || ''} disabled />
                        </div>
                        <div className="space-y-2">
                            <Label>{t('profile.verband.fee', { defaultValue: 'Aktueller Beitrag' })}</Label>
                            <Input value={user.membership?.current_fee !== undefined ? `${user.membership.current_fee.toFixed(2)} €` : ''} disabled />
                            <p className="text-xs text-muted-foreground mt-1">Siehe <a href="#" target="_blank" className="underline">Satzung</a> und <a href="#" target="_blank" className="underline">Beitragsordnung</a></p>
                        </div>
                        <div className="space-y-2">
                            <Label>Art der Mitgliedschaft</Label>
                            <Input value={user?.membership?.type === 'active' ? 'Aktivmitgliedschaft' : user?.membership?.type === 'supporting' ? 'Fördernde Mitgliedschaft' : user?.membership?.type === 'ordinary' ? 'Ordentliche Mitgliedschaft' : (user?.membership?.type || '')} disabled />
                        </div>
                        <div className="space-y-2">
                            <Label>Stimmenanzahl</Label>
                            <Input value={user?.membership?.current_votes !== undefined ? user.membership.current_votes.toString() : '0'} disabled />
                        </div>
                    </div>
                </CardContent>
            </Card>

            {/* Action Modal equivalent inline */}
            {
                actionModal && (
                    <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4">
                        <Card className="w-full max-w-md shadow-lg border">
                            <CardHeader>
                                <CardTitle>
                                    {actionModal === 'apply' ? t('profile.actions.apply_membership') : t('profile.actions.cancel_membership')}
                                </CardTitle>
                                <CardDescription>
                                    {actionModal === 'apply'
                                        ? 'Bitte wähle aus, ab wann du aktiv werden möchtest.'
                                        : 'Bitte wähle aus, zu wann du kündigen möchtest.'}
                                </CardDescription>
                            </CardHeader>
                            <CardContent className="space-y-4">
                                {actionModal === 'cancel' ? (
                                    <div className="space-y-2">
                                        <Label htmlFor="actionDate">Ende (Optional)</Label>
                                        <Input
                                            id="actionDate"
                                            type="date"
                                            value={actionDate}
                                            onChange={(e) => setActionDate(e.target.value)}
                                        />
                                        <p className="text-xs text-muted-foreground pt-1">
                                            Wenn du das Datum leer lässt, wird die Kündigung sofort wirksam.
                                        </p>
                                    </div>
                                ) : (
                                    <div className="space-y-4 pt-2">
                                        <div className="space-y-2 border-b pb-4">
                                            <Label>Art der Mitgliedschaft</Label>
                                            <div className="flex flex-col gap-2">
                                                <Label className="flex items-center gap-2 cursor-pointer font-normal">
                                                    <input type="radio" value="active" checked={applyType === 'active'} onChange={() => setApplyType('active')} />
                                                    Aktivmitgliedschaft (10 € / Jahr)
                                                </Label>
                                                <Label className="flex items-center gap-2 cursor-pointer font-normal">
                                                    <input type="radio" value="supporting" checked={applyType === 'supporting'} onChange={() => setApplyType('supporting')} />
                                                    Fördernde Mitgliedschaft
                                                </Label>
                                            </div>
                                        </div>
                                        {applyType === 'supporting' && (
                                            <div className="space-y-2 animate-in fade-in pb-2">
                                                <Label htmlFor="customFee">Wunschbeitrag pro Jahr (€)</Label>
                                                <Input
                                                    id="customFee"
                                                    type="number"
                                                    min="1"
                                                    step="1"
                                                    value={applyFee}
                                                    onChange={(e) => setApplyFee(Number(e.target.value))}
                                                />
                                            </div>
                                        )}
                                        <div className="space-y-3">
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-privacy" className="mt-1" checked={consents.privacy} onChange={(e) => setConsents(p => ({ ...p, privacy: e.target.checked }))} />
                                                <Label htmlFor="consent-privacy" className="text-sm font-normal leading-snug">
                                                    {t('club.details.membership.consent_privacy', { defaultValue: 'Ich stimme der Datenschutzerklärung zu.' })}
                                                </Label>
                                            </div>
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-accuracy" className="mt-1" checked={consents.accuracy} onChange={(e) => setConsents(p => ({ ...p, accuracy: e.target.checked }))} />
                                                <Label htmlFor="consent-accuracy" className="text-sm font-normal leading-snug">
                                                    {t('club.details.membership.consent_accuracy', { defaultValue: 'Ich versichere, dass meine Angaben der Wahrheit entsprechen.' })}
                                                </Label>
                                            </div>
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-statutes" className="mt-1" checked={consents.statutes} onChange={(e) => setConsents(p => ({ ...p, statutes: e.target.checked }))} />
                                                <Label htmlFor="consent-statutes" className="text-sm font-normal leading-snug">
                                                    Ich habe die <a href="#" target="_blank" className="underline text-blue-600">Satzung</a> gelesen und erkenne sie an.
                                                </Label>
                                            </div>
                                            <div className="flex items-start space-x-2">
                                                <input type="checkbox" id="consent-finances" className="mt-1" checked={consents.finances} onChange={(e) => setConsents(p => ({ ...p, finances: e.target.checked }))} />
                                                <Label htmlFor="consent-finances" className="text-sm font-normal leading-snug">
                                                    Ich habe die <a href="#" target="_blank" className="underline text-blue-600">Beitragsordnung</a> gelesen und erkenne sie an.
                                                </Label>
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </CardContent>
                            <CardFooter className="justify-end gap-2 bg-muted/20 py-4">
                                <Button variant="ghost" onClick={() => setActionModal(null)} disabled={actionLoading}>
                                    {t('club.details.actions.cancel', { defaultValue: 'Abbrechen' })}
                                </Button>
                                <Button
                                    variant={actionModal === 'apply' ? 'default' : 'destructive'}
                                    onClick={() => handleMembershipAction(actionModal)}
                                    disabled={actionLoading || (actionModal === 'apply' && (!consents.privacy || !consents.accuracy || !consents.statutes || !consents.finances))}
                                >
                                    {actionLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                                    {actionModal === 'apply' ? t('club.details.membership.apply_button', { defaultValue: 'Antrag stellen' }) : t('club.details.membership.cancel_button', { defaultValue: 'Kündigen' })}
                                </Button>
                            </CardFooter>
                        </Card>
                    </div>
                )
            }
        </div >
    );
}
